---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gogs-triggerbinding
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: gitshortsha
    value: $(body.short_sha)
  - name: gitbranchname
    value: $(body.branch_name)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: contenttype
    value: $(header.Content-Type)