---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: petclinic-trigger-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitshortsha
    description: The short commit sha
    default: master
  - name: gitbranchname
    description: The branch name
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: petclinic-build-
      # name: petclinic-dev-$(tt.params.gitbranchname)-$(tt.params.gitshortsha)
      labels:
        tekton.dev/pipeline: petclinic-build
    spec:
      pipelineRef:
        name: petclinic-build
      params:
        - name: APP_SOURCE_GIT
          value: $(tt.params.gitrepositoryurl)
        - name: APP_SOURCE_REVISION
          value: $(tt.params.gitrevision)
        - name: APP_IMAGE_TAG
          value: $(tt.params.gitbranchname)-$(tt.params.gitshortsha)
      workspaces:
      - name: maven-settings
        configMap:
          name: maven-settings
      - name: workspace
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            volumeMode: Filesystem